pipelines:
  - name: pipeline_pd
    steps:
      - name: bash_pagerduty_success
        type: Bash
        configuration:
          integrations:
            - name: pagerduty
        execution:
          onStart:
            - echo "starting"
          onExecute:
            - send_notification pagerduty -text "hello world from JFrog Pipelines run number $run_number"
